### PR TITLE
Update to v1.18.4

### PR DESCRIPTION
**Pull request by dsd**
https://phabricator.endlessm.com/T10888

### CODE REVIEW

**Comment by dbnicholson** [comment]
@dsd Merge looks great, but there seems to be one commit left that was only done on the 1.17 branch upstream but is not upstream. See cb58274c98654f1b0a8e069c9deeeadf9641d951. When I diff Version_1.18.4..T10888, that's the only non-Endless change I see.

Do you think we can drop that commit so that we only have Endless changes on top of 1.18.4?

**Comment by dsd** [comment]
I hadn't noticed that slight discontinuity in the history. I agree we should sync to 1.18 more precisely. Should I just revert that commit on top of this merge, or is there some other trick?

**Comment by dbnicholson** [comment]
It looks like you did a merge, so I think the only way would be a revert. You could just do a rebase and filter unwanted commits, though.

**Comment by dsd** [comment]
I chose to merge it thinking that the history was linear. I might have instead rebased it if I had spotted this divergance before starting. Anyway, here is a revert commit on top.

**Comment by dbnicholson** [comment]
Looks good. Feel free to push the branch and tag.

**Comment by dbnicholson** [comment]
In the future (and for the debhelper merge), I'd prefer to push the branch to master rather than doing a merge with github. It avoids a useless merge commit from github and ensures that this head is really master.

**Pull request merged**
